### ISSUE TITLE
Unable to load lots of images

### ISSUE THREAD

**Issue by Nialixus** [salih-demir/animation-view#1]
Hy there i tried to load 80 images using your code, but it doesn't work.
Is there any way i can achieve that?

**Comment by salih-demir** [comment]
Hi,

Is there any way to send me those images for me to detect the problem? Does it throw OutOfMemoryException?

**Comment by Nialixus** [comment]
I'm using 80 Images from Rajawali Repository : https://github.com/Rajawali/Rajawali/tree/master/examples/src/main/res/drawable-nodpi

Sorry, but i forgot to see the logcat and found alternative solution on displaying a lots of images.

But yesterday when i tried yours, it takes a lot of time to open activity where animationview exist, and failed to open the activity but it doesn't forced close, instead it's automatically go back to mainactivity.

**Comment by salih-demir** [comment]
Hello Nialixus,

I run the application with your images and it run as expected. CPU and memory consumption is also acceptable. Can you please specific your problem a little more?
This class is solely intended to animate sequences of images linearly. If you want to control the animation progress or use complex animations, I suggest you to use [LottieAnimationView](https://github.com/airbnb/lottie-android).

![screenshot](https://user-images.githubusercontent.com/19192169/63536183-bf8d2d00-c51b-11e9-81f8-6b19371a8f8f.png)

Thank you for your interest.

**Comment by Nialixus** [comment]
Probably my activity contains something that consumpt lots of memories, and that's why i can't use it together with your dependency. But thank you for the answer and suggestion. (•̀ᴗ•́)و ̑̑
